// lints the inline script extracted from index.html (see scan-js)
export default [
  {
    files: ['page-scan.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        document: 'readonly', window: 'readonly', localStorage: 'readonly',
        sessionStorage: 'readonly', location: 'readonly', navigator: 'readonly',
        history: 'readonly', fetch: 'readonly', setTimeout: 'readonly',
        setInterval: 'readonly', clearTimeout: 'readonly', clearInterval: 'readonly',
        requestAnimationFrame: 'readonly', MutationObserver: 'readonly',
        IntersectionObserver: 'readonly', ResizeObserver: 'readonly',
        BroadcastChannel: 'readonly', Audio: 'readonly', Image: 'readonly',
        HTMLImageElement: 'readonly', Element: 'readonly', Node: 'readonly',
        CSS: 'readonly', URL: 'readonly', URLSearchParams: 'readonly',
        addEventListener: 'readonly', removeEventListener: 'readonly',
        getComputedStyle: 'readonly', caches: 'readonly', alert: 'readonly',
        confirm: 'readonly', prompt: 'readonly', Twitch: 'readonly',
        TreeWalker: 'readonly', NodeFilter: 'readonly', Range: 'readonly',
        DOMParser: 'readonly', CustomEvent: 'readonly', KeyboardEvent: 'readonly',
        PointerEvent: 'readonly', MouseEvent: 'readonly', WheelEvent: 'readonly',
        TouchEvent: 'readonly', Event: 'readonly', Intl: 'readonly',
        matchMedia: 'readonly', screen: 'readonly', open: 'readonly',
        console: 'readonly', performance: 'readonly', Date: 'readonly',
        FileReader: 'readonly', Blob: 'readonly', FormData: 'readonly',
        XMLHttpRequest: 'readonly', Notification: 'readonly',
        visualViewport: 'readonly', devicePixelRatio: 'readonly',
        innerWidth: 'readonly', innerHeight: 'readonly',
        scrollTo: 'readonly', scrollY: 'readonly', scrollX: 'readonly',
        requestIdleCallback: 'readonly', queueMicrotask: 'readonly',
        structuredClone: 'readonly', AbortController: 'readonly',
        AbortSignal: 'readonly',
        indexedDB: 'readonly', IDBKeyRange: 'readonly',
        SpeechSynthesisUtterance: 'readonly', speechSynthesis: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-dupe-keys': 'error', 'no-duplicate-case': 'error',
      'no-fallthrough': 'warn', 'no-unreachable': 'error',
      'no-redeclare': 'error', 'no-self-assign': 'error',
      'no-unused-labels': 'error', 'no-useless-escape': 'warn',
      'no-cond-assign': ['warn', 'except-parens'],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'valid-typeof': 'error', 'no-unsafe-negation': 'error',
      'no-compare-neg-zero': 'error', 'no-loss-of-precision': 'error',
      'no-irregular-whitespace': 'warn',
    },
  },
];
